"""Generate ``docs/supported-formats.md`` from the code that actually carves.

A hand-maintained format table goes stale the first time somebody adds a
signature and forgets the document; ``docs/performance/benchmark.md`` carried
one that still said seven formats had no signature months after they gained
one. This document is instead produced from three registries:

* the signature table, :func:`core.carve.signature.load_signatures`, which is
  what the scanner matches;
* :data:`core.carve.structure.PARSERS`, which derive an object's exact length
  from its own structure;
* :data:`core.carve.validate.VALIDATORS`, which hand the bytes to a decoder.

``tests/scripts/test_supported_formats_doc.py`` regenerates it and fails if the
committed file differs, so the table cannot silently drift from the code.

    python scripts/gen_supported_formats.py            # rewrite the doc
    python scripts/gen_supported_formats.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

DOC = ROOT / "docs" / "supported-formats.md"

#: What the reassembler for each format accepts, in the table's words.
_REASSEMBLY_SCOPE = {
    "JPEG": "yes (baseline only)",
    "PNG": "yes (chunk CRC + exact zlib length)",
}


def render() -> str:
    from core.carve.signature import load_signatures
    from core.carve.structure import _FRAGMENT_CAPABLE, PARSERS
    from core.carve.validate import VALIDATORS

    signatures = sorted(load_signatures(), key=lambda item: (item.ext, item.name))
    lines = [
        "# Supported formats",
        "",
        "<!-- GENERATED by scripts/gen_supported_formats.py. Do not edit by hand;",
        "     tests/scripts/test_supported_formats_doc.py fails if this drifts. -->",
        "",
        "Every row below is read from the code, not written about it. **Signature**",
        "means the scanner matches the format's header. **Structure parser** means",
        "the object's exact end is derived from the format's own length fields;",
        "without one, the end is the footer or the next header of any type.",
        "**Decoder** means a real decoder validates the recovered bytes and its",
        "verdict is a score component. **Bifragment reassembly** is attempted only",
        "where marked, and only for an object in exactly two runs.",
        "",
        "| Signature | Extension | Structure parser | Decoder "
        "| Bifragment reassembly |",
        "|---|---|---|---|---|",
    ]
    for signature in signatures:
        parser = PARSERS.get(signature.name)
        reassembly = (
            _REASSEMBLY_SCOPE.get(signature.name, "yes")
            if signature.name in _FRAGMENT_CAPABLE
            else "no"
        )
        lines.append(
            f"| {signature.name} | `{signature.ext}` "
            f"| {'yes (`' + parser.__name__ + '`)' if parser else 'no'} "
            f"| {'yes' if signature.ext in VALIDATORS else 'no'} "
            f"| {reassembly} |"
        )
    lines += [
        "",
        f"{len(signatures)} signatures, {len(PARSERS)} parser registrations, "
        f"{len(VALIDATORS)} decoder registrations.",
        "",
        "Decoders are also registered for these extensions, which a signature",
        "above resolves to or which the undelete pass names from filesystem",
        "metadata:",
        "",
        ", ".join(
            f"`{ext}`" for ext in sorted(set(VALIDATORS) - {s.ext for s in signatures})
        )
        or "none",
        "",
        "## Filesystems (undelete)",
        "",
        "Read through The Sleuth Kit (`pytsk3`): NTFS, FAT12/16/32, exFAT, ext2,",
        "ext3, ext4. ext4 undelete recovers essentially nothing by design, because",
        "the kernel zeroes the extent tree on unlink; see `docs/limitations.md`.",
        "APFS, HFS+, XFS and Btrfs are not supported for undelete; objects on them",
        "are still reachable by signature and structure carving.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = DOC.read_text(encoding="utf-8") if DOC.exists() else ""
        if current != text:
            print(f"{DOC} is stale; run scripts/gen_supported_formats.py")  # noqa: T201
            return 1
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC}")  # noqa: T201
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
